import { Inter } from 'next/font/google'
import './globals.css'
import UserContextProvider from '../context/UserContextProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en" className='flex-grow'>
      <body className={inter.className}>
        <UserContextProvider>
          {children}
        </UserContextProvider>

      </body>
    </html>

  )
}
